import { randomBytes } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
	normalizeRemote,
	parseGitConfigRemote,
} from "@jmtrin/kevin-core";

const LF_CONFIG = `[core]
	repositoryformatversion = 0
[remote "origin"]
	url = https://github.com/Acme/App.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
`;

const CRLF_TAB_CONFIG = LF_CONFIG.replace(/\n/g, "\r\n").replace(
	/\turl = /g,
	"\t\turl = ",
);

describe("parseGitConfigRemote — .git/config INI reader", () => {
	it('returns the url of [remote "origin"]', () => {
		expect(parseGitConfigRemote(LF_CONFIG)).toBe(
			"https://github.com/Acme/App.git",
		);
	});

	it("parses a CRLF, tab-indented config identically to its LF, space-indented twin", () => {
		expect(parseGitConfigRemote(CRLF_TAB_CONFIG)).toBe(
			parseGitConfigRemote(LF_CONFIG),
		);
	});

	it("returns the first url inside the named section", () => {
		const config = `[remote "origin"]
	url = first
	url = second
`;
		expect(parseGitConfigRemote(config)).toBe("first");
	});

	it("ignores comments and empty lines", () => {
		const config = `# generated by some tool
; another comment

[remote "origin"]
	# url for ci
	url = https://ci.example/team/app
`;
		expect(parseGitConfigRemote(config)).toBe("https://ci.example/team/app");
	});

	it("only matches the requested remote name", () => {
		const config = `[remote "origin"]
	url = https://github.com/team/real.git
[remote "upstream"]
	url = https://github.com/team/upstream.git
`;
		expect(parseGitConfigRemote(config)).toBe(
			"https://github.com/team/real.git",
		);
		expect(parseGitConfigRemote(config, "upstream")).toBe(
			"https://github.com/team/upstream.git",
		);
		expect(parseGitConfigRemote(config, "missing")).toBeNull();
	});

	it("returns null for a config with no [remote] section", () => {
		const config = `[core]
	repositoryformatversion = 0
[branch "main"]
	remote = origin
`;
		expect(parseGitConfigRemote(config)).toBeNull();
	});

	it("returns null when the only remote is named upstream", () => {
		const config = `[remote "upstream"]
	url = https://github.com/team/app.git
`;
		expect(parseGitConfigRemote(config)).toBeNull();
	});

	it("returns null for an empty string", () => {
		expect(parseGitConfigRemote("")).toBeNull();
	});

	it("returns null for a single NUL byte", () => {
		expect(parseGitConfigRemote("\u0000")).toBeNull();
	});

	it("never throws on 1 MB of random bytes", () => {
		const blob = randomBytes(1024 * 1024).toString("latin1");
		expect(() => parseGitConfigRemote(blob)).not.toThrow();
	});

	it("never throws on a section header without a closing bracket", () => {
		expect(() =>
			parseGitConfigRemote('[remote "origin"\n\turl = x'),
		).not.toThrow();
	});

	it("never throws on a key line without an equals sign", () => {
		const config = `[remote "origin"]
	url
	url = ok
`;
		expect(() => parseGitConfigRemote(config)).not.toThrow();
	});
});

describe("normalizeRemote — URL folding", () => {
	it("normalizes all five plan §5.1 fixtures to their stated outputs", () => {
		expect(normalizeRemote("https://github.com/Acme/App.git")).toBe(
			"github.com/acme/app",
		);
		expect(normalizeRemote("git@github.com:Acme/App.git")).toBe(
			"github.com/acme/app",
		);
		expect(normalizeRemote("ssh://git@github.com/Acme/App")).toBe(
			"github.com/acme/app",
		);
		expect(normalizeRemote("https://user:token@gitlab.com/team/svc.git")).toBe(
			"gitlab.com/team/svc",
		);
		expect(normalizeRemote("/srv/git/bare.git")).toBeNull();
	});

	it("strips credentials before anything can retain a copy", () => {
		const out = normalizeRemote("https://user:token@gitlab.com/team/svc.git");
		expect(out).not.toBeNull();
		expect(out).not.toContain("@");
		expect(out).not.toContain("token");
		const host = out?.split("/")[0] ?? "";
		expect(host).not.toContain(":");
	});

	it("lowercases the host and path so two clones agree", () => {
		expect(normalizeRemote("https://GitHub.com/Acme/App.git")).toBe(
			"github.com/acme/app",
		);
	});

	it("drops a trailing slash", () => {
		expect(normalizeRemote("https://github.com/acme/app/")).toBe(
			"github.com/acme/app",
		);
	});

	it("returns null for a bare host with no path", () => {
		expect(normalizeRemote("https://github.com")).toBeNull();
	});

	it("returns null for a file:// remote (local path)", () => {
		expect(normalizeRemote("file:///srv/git/bare.git")).toBeNull();
	});

	it("returns null for an empty string", () => {
		expect(normalizeRemote("")).toBeNull();
	});

	it("BUG-004: strips a numeric port so transport forms fold to one id", () => {
		expect(normalizeRemote("https://git.example.com:8443/org/repo.git")).toBe(
			"git.example.com/org/repo",
		);
		expect(normalizeRemote("ssh://git@host:2222/org/repo.git")).toBe(
			"host/org/repo",
		);
		expect(normalizeRemote("git@host:org/repo.git")).toBe("host/org/repo");
		expect(normalizeRemote("https://host:443/org/repo.git")).toBe(
			"host/org/repo",
		);
		// The scp-style path form (non-digit after the colon) is
		// untouched by the port strip.
		expect(normalizeRemote("git@host:App/repo.git")).toBe("host/app/repo");
		// A root URL with only a port has no path → falls through.
		expect(normalizeRemote("https://host:8443")).toBeNull();
	});
});

describe("K8-005 source hygiene", () => {
	it("plugin/RepoIdentity.ts contains no child_process, execSync or spawn", () => {
		const src = readFileSync(
			join(process.cwd(), "plugin", "RepoIdentity.ts"),
			"utf8",
		);
		expect(src).not.toContain("child_process");
		expect(src).not.toContain("execSync");
		expect(src).not.toContain("spawn");
	});
});
